// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package mypack

/*
package用语句，或者命令行的import_path=mypackage
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnumCode int32

const (
	EnumCode_UNKNOWN EnumCode = 0
	EnumCode_E1      EnumCode = 4
	EnumCode_E2      EnumCode = 5
)

var EnumCode_name = map[int32]string{
	0: "UNKNOWN",
	4: "E1",
	5: "E2",
}
var EnumCode_value = map[string]int32{
	"UNKNOWN": 0,
	"E1":      4,
	"E2":      5,
}

func (x EnumCode) String() string {
	return proto.EnumName(EnumCode_name, int32(x))
}
func (EnumCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_test_e9ac2eff275909fb, []int{0}
}

type LoginC2S struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	List                 []int64  `protobuf:"varint,3,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginC2S) Reset()         { *m = LoginC2S{} }
func (m *LoginC2S) String() string { return proto.CompactTextString(m) }
func (*LoginC2S) ProtoMessage()    {}
func (*LoginC2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e9ac2eff275909fb, []int{0}
}
func (m *LoginC2S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginC2S.Unmarshal(m, b)
}
func (m *LoginC2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginC2S.Marshal(b, m, deterministic)
}
func (dst *LoginC2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginC2S.Merge(dst, src)
}
func (m *LoginC2S) XXX_Size() int {
	return xxx_messageInfo_LoginC2S.Size(m)
}
func (m *LoginC2S) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginC2S.DiscardUnknown(m)
}

var xxx_messageInfo_LoginC2S proto.InternalMessageInfo

func (m *LoginC2S) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginC2S) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginC2S) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type LoginS2C struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginS2C) Reset()         { *m = LoginS2C{} }
func (m *LoginS2C) String() string { return proto.CompactTextString(m) }
func (*LoginS2C) ProtoMessage()    {}
func (*LoginS2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e9ac2eff275909fb, []int{1}
}
func (m *LoginS2C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginS2C.Unmarshal(m, b)
}
func (m *LoginS2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginS2C.Marshal(b, m, deterministic)
}
func (dst *LoginS2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginS2C.Merge(dst, src)
}
func (m *LoginS2C) XXX_Size() int {
	return xxx_messageInfo_LoginS2C.Size(m)
}
func (m *LoginS2C) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginS2C.DiscardUnknown(m)
}

var xxx_messageInfo_LoginS2C proto.InternalMessageInfo

func (m *LoginS2C) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginC2S)(nil), "mypack.LoginC2S")
	proto.RegisterType((*LoginS2C)(nil), "mypack.LoginS2C")
	proto.RegisterEnum("mypack.EnumCode", EnumCode_name, EnumCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	DoLogin(ctx context.Context, in *LoginC2S, opts ...grpc.CallOption) (*LoginS2C, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) DoLogin(ctx context.Context, in *LoginC2S, opts ...grpc.CallOption) (*LoginS2C, error) {
	out := new(LoginS2C)
	err := c.cc.Invoke(ctx, "/mypack.Login/doLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	DoLogin(context.Context, *LoginC2S) (*LoginS2C, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_DoLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).DoLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mypack.Login/DoLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).DoLogin(ctx, req.(*LoginC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mypack.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "doLogin",
			Handler:    _Login_DoLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_e9ac2eff275909fb) }

var fileDescriptor_test_e9ac2eff275909fb = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0xad, 0x2c, 0x48, 0x4c, 0xce, 0x56, 0x72,
	0xe2, 0xe2, 0xf0, 0xc9, 0x4f, 0xcf, 0xcc, 0x73, 0x36, 0x0a, 0x16, 0xe2, 0xe3, 0x62, 0xca, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x39, 0x99, 0xc5,
	0x25, 0x12, 0xcc, 0x0a, 0xcc, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x92, 0x1c, 0xd4, 0x8c, 0x60, 0x23,
	0x67, 0x90, 0x7c, 0x72, 0x7e, 0x4a, 0x2a, 0xd4, 0x14, 0x30, 0x5b, 0x4b, 0x9d, 0x8b, 0xc3, 0x35,
	0xaf, 0x34, 0xd7, 0x39, 0x3f, 0x25, 0x55, 0x88, 0x9b, 0x8b, 0x3d, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f,
	0xdc, 0x4f, 0x80, 0x41, 0x88, 0x8d, 0x8b, 0xc9, 0xd5, 0x50, 0x80, 0x05, 0x4c, 0x1b, 0x09, 0xb0,
	0x1a, 0x59, 0x70, 0xb1, 0x82, 0x0d, 0x12, 0xd2, 0xe7, 0x62, 0x4f, 0xc9, 0x87, 0x30, 0x05, 0xf4,
	0x20, 0x2e, 0xd5, 0x83, 0x39, 0x53, 0x0a, 0x55, 0x24, 0xd8, 0xc8, 0x59, 0x89, 0x21, 0x89, 0x0d,
	0xec, 0x2b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x96, 0xd2, 0x10, 0xe3, 0x00, 0x00,
	0x00,
}
